### PR TITLE
Experimental support for osx-arm64 (Apple M1)

### PR DESCRIPTION
**Pull request by hkratz**
This is an unofficial experimental patch to make the GitHub Actions Runner work on Apple Silicon.

**Try out the version based on v2.291.1:**
```
git clone https://github.com/hkratz/gha-runner-osx-arm64.git -b macos-arm64
cd gha-runner-osx-arm64/src/
./dev.sh layout
cd ../_layout/
./config.sh --url  {repo-url} --token AA... # use your repo URL and your runner registration token
```

**Known issues:**
* Auto-updates are disabled as this is not an official runner.

**Changes compared to upstream release:**
* Fall back to Node 16 instead of Node 12 as earlier versions do not support ARM64.
* Add osx-arm64 runtime identifier at various places and remove implicit assumption that Darwin/osx implies X64 arch.
* Fixed failing test `DetermineNodeRuntimeVersionInAlpineContainerAsync`, which apparently requires x86-64 to pass.
* Disable auto-update on Macos ARM64.
* Add checksums for dotnet runtime and externals.
* Minor: Print checksum of dotnet runtime and externals in assertion failure.

Hacks could possibly be removed in the future.

### CODE REVIEW

**Comment by paulz** [comment]
Thank you, would love to try it. 

What is the repo-url in this context?

And where we can lookup the runner registration token? Is there a file on our self hosted runner?

**Comment by hkratz** [comment]
> Thank you, would love to try it.
> 
> What is the repo-url in this context?
> 
> And where we can lookup the runner registration token? Is there a file on our self hosted runner?

@paulz Navigate to the  Actions -> Runner section of your repository settings and press the `Add runner` button. Use the URL and token from the `$ ./config.sh --url ...` command in the **Configure** section.

**Comment by hkratz** [comment]
Rebased on v2.282.1.

**Comment by whalemare** [comment]
How to disable auto-update?

After one day of using I have next message:

`./run.sh`

```
√ Connected to GitHub

2021-09-24 08:35:52Z: Listening for Jobs
An error occurred: A package with type agent, platform osx-arm64, version 2.283.1 was not found.
```

I suppose this is exist, because runner try to update themselves

---

Yes, after changing [code version detection](https://github.com/NixOS/nixpkgs/pull/137673/files?file-filters%5B%5D=.nix&file-filters%5B%5D=.patch&hide-deleted-files=true#diff-29876ec8f6cf929689bf152f5ed2eceaf6ac194ab6202aac5fda0b333868a182), runner start works again

**Comment by hkratz** [comment]
I currently plan to automate rebasing+testing whenever a new version is released.

**Comment by hkratz** [comment]
Rebased on v2.284.0 and updated to use the release version of .NET 6.0.

**Comment by hkratz** [comment]
Updated to v2.285.0, fixed a new failing test and disabled auto-updates.

**Comment by alexanderedge** [comment]
I updated our runner to the [latest commit](https://github.com/hkratz/gha-runner-osx-arm64/pull/2/commits/364788f453a3f06cb6f68f8b33a6fc1e8dbc009b) and it doesn't appear to be picking up jobs any longer. Is anyone else seeing this?

**Comment by hkratz** [comment]
> I updated our runner to the [latest commit](https://github.com/hkratz/gha-runner-osx-arm64/pull/2/commits/364788f453a3f06cb6f68f8b33a6fc1e8dbc009b) and it doesn't appear to be picking up jobs any longer. Is anyone else seeing this?

@alexanderedge That is most likely the version check. I have updated the PR to the latest version. Please try again with that one.

**Comment by alexanderedge** [comment]
> > I updated our runner to the [latest commit](https://github.com/hkratz/gha-runner-osx-arm64/pull/2/commits/364788f453a3f06cb6f68f8b33a6fc1e8dbc009b) and it doesn't appear to be picking up jobs any longer. Is anyone else seeing this?
> 
> @alexanderedge That is most likely the version check. I have updated the PR to the latest version. Please try again with that one.

Yes, working perfectly again now. Thank you 🥇

**Comment by hkratz** [comment]
Updated to v2.286.0. .NET 6.0 support and one test fix are now upstream, so the diff has gotten smaller.

**Comment by Leo-Schmit** [comment]
Hello,
Something wrong...how can I fix this?

a@as-Mac src % ./dev.sh layout
~/gha-runner-osx-arm64/src ~/gha-runner-osx-arm64/src
Prepend /Users/a/gha-runner-osx-arm64/src/../_dotnetsdk/6.0.100 to %PATH%

-----------------------------------------
  Dotnet SDK Version
-----------------------------------------
Unhandled exception. System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.Cli.Utils.Reporter' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.ConsolePal' threw an exception.
 ---> System.OutOfMemoryException: Array dimensions exceeded supported range.
   at System.ConsolePal..cctor()
   --- End of inner exception stack trace ---
   at System.Console.get_ForegroundColor()
   at Microsoft.DotNet.Cli.Utils.AnsiConsole..ctor(TextWriter writer)
   at Microsoft.DotNet.Cli.Utils.Reporter.Reset()
   at Microsoft.DotNet.Cli.Utils.Reporter..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.Cli.Utils.Reporter.get_Error()
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
./dev.sh: line 323: 11569 Abort trap: 6           dotnet --version

**Comment by whalemare** [comment]
I am using latest commit deb481e4, but runner just stuck and not pickup any jobs

Снимок экрана 2022-01-23 в 11 31 59

---

Version in commit 071a9ba145953c2c9f28ba2705bc62e4c3e70a09 works nicely when I apply patch from [my previous message](https://github.com/hkratz/gha-runner-osx-arm64/pull/2#issuecomment-926453010)

**Comment by hkratz** [comment]
Rebased on v2.287.1, dropped another hack (no longer needed).

**Comment by mrweiland** [comment]
Thank you so much for doing this - seems to work. 👍👍👍👍👍Keep on do great work. 👍

**Comment by david13Lopez** [comment]
Hey, I'm using that runner, but the runner is not taking any job, can someone help me?

**Comment by hkratz** [comment]
> Hey, I'm using that runner, but the runner is not taking any job, can someone help me?

Probably needs an update. I will look into it shortly.

**Comment by david13Lopez** [comment]
> > Hey, I'm using that runner, but the runner is not taking any job, can someone help me?
> 
> Probably needs an update. I will look into it shortly.

Okay thanks. Waiting for it! :)

**Comment by codin-play** [comment]
> > Hey, I'm using that runner, but the runner is not taking any job, can someone help me?
> 
> Probably needs an update. I will look into it shortly.

Super appreciative of your work on this. Any chance you could look into this? I would love to give it a test drive. It's still crazy to me the support for M1 doesn't exist yet as it is the only chip you can buy for machines. Thanks again!

**Comment by hkratz** [comment]
Rebased on the most current version, v2.289.1. It was a bit more involved due to new checksum code. 

Should work again now, running the build of this repo with a runner on my M1 Mac worked fine.

**Comment by ahoereth** [comment]
Again had to rebase for it to pickup jobs. Sadly cannot contribute here as I would need to overwrite your changes, but the following did the job:

```bash
git remote add github git@github.com:actions/runner.git
git pull github main
git rebase -X ours main
```

Had to rerun `config.sh` tho.

Thanks for the work!

**Comment by hkratz** [comment]
Updated to v2.289.2.

**Comment by hkratz** [comment]
> ```shell
> git remote add github git@github.com:actions/runner.git
> git pull github main
> git rebase -X ours main
> ```
@ahoereth Better not to rebase on `main`, because it frequently contains unreleased changes. Instead rebase on the most current release branch. The current release branch is `releases/m289`.

**Comment by hkratz** [comment]
Updated to v2.290.0.

**Comment by daiyam** [comment]
> > ```shell
> > git remote add github git@github.com:actions/runner.git
> > git pull github main
> > git rebase -X ours main
> > ```
> 
> @ahoereth Better not to rebase on `main`, because it frequently contains unreleased changes. Instead rebase on the most current release branch. The current release branch is `releases/m289`.

I had also to rebase with `releases/m290` so the jobs can be picked up. Thx for your work.

**Comment by hkratz** [comment]
Updated to v2.290.1.

**Comment by runmael** [comment]
Hey @hkratz thanks for providing the ARM64 runner, I went and installed it but it seems the runner isn't picking any jobs. Based on discussion, it seems that rebasing usually helped, but even with rebasing to the latest release (`releases/m291`) it still isn't picking any jobs. Could you jump in and check why is this happening, or provide some steps how to reenable it in those situations? Thank you

**Comment by daiyam** [comment]
I did had to rebase my runner to `releases/m291` and it's picking the jobs.

Here my commands:
```
git remote add github https://github.com/actions/runner.git

git pull github releases/m291
git update-ref -d MERGE_HEAD
git rebase -X ours github/releases/m291
```

**Comment by hkratz** [comment]
Updated to v2.291.1.

**Comment by hkratz** [comment]
No longer needed as the functionality is implemented upstream.

**Pull request closed without merging**
